SHOULD WORK

diff --git a/Initial_Setup/initial_config b/Initial_Setup/initial_config
--- a/Initial_Setup/initial_config
+++ b/Initial_Setup/initial_config
@@ -5,7 +5,7 @@ if [[ $(/usr/bin/id -u) -ne 0 ]]
 then
     echo "CRITICAL ERROR: Not running as root"
     exit
-f
+fi
 
 # PATH TO CONFIG FILE IN "/etc/sysctl.d/"
 kernelConfig="/etc/sysctl.d/net.conf"
@@ -17,8 +17,18 @@ arpAnnounce="net.ipv4.conf.all.arp_announce=1"
 arpIgnore="net.ipv4.conf.all.arp_ignore=1"
 
 # setting variables for crontab run
-crontabNormal='*/1 * * * * cd /usr/local/projects/wifi_connectivity_bot && ./wifiConnBot_run.py 1'
-crontabSummary='0 12 * * 7 cd /usr/local/projects/wifi_connectivity_bot && ./wifiConnBot_run.py 0'
+echo "Enter the minute frequency to tweet when the Wifi goes down:"
+read minutes
+while ! ( [ "$minutes" -eq "$minutes" ] && [ "$minutes" -gt 10 ] && [ "$minutes" -lt 240 ] ) 2>/dev/null
+do
+   echo "Minutes variable invalid."
+   echo "Enter a minutes value between 10 and 240" 
+   read minutes
+done
+
+crontabNormal="*/$minutes * * * * cd /usr/local/projects/wifi_connectivity_bot && ./wifiConnBot_run.py 1"
+echo "$crontabNormal"
+crontabSummary="0 12 * * 7 cd /usr/local/projects/wifi_connectivity_bot && ./wifiConnBot_run.py 0"
 
 # sets kernel variables to allow for connections
 # through two different interfaces.
@@ -48,6 +58,6 @@ set_kernel $arpAnnounce
 set_kernel $arpIgnore
 
 # sets system to shutdown in one minute
-/sbin/shutdown -r -h +1
+#/sbin/shutdown -r -h +1
 # deletes setup file
-rm initial_config
+#rm initial_config
